server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/spring
    username: root
    password: hyun
  jpa-config:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mybatis-config:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    view:
      prefix: webapp/WEB-INF/jsp
      suffix: .jsp